import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Velvet Rose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#f5dee4] h-screen overflow-hidden flex flex-col items-center justify-center md:justify-start lg:mt-0 md:mt-20 -mt-16'>
        <img src="/logo.jpg" alt="Logo" className='md:h-[500px] mx-auto' />
        <button
          className='bg-[#7f0f1e] hover:bg-[#f5dee4] hover:border hover:border-[#7f0f1e] text-[20px] hover:text-[#7f0f1e] font-thin uppercase text-white md:w-[20%] w-[70%] mx-auto py-2 md:-mt-28 -mt-10 rounded-lg'
          onClick={() => router.push('/homepage')}
        >
          Enter
        </button>
      </div>
    </div>
  )
}
